Proj 1 vector operations
GreySR/made-cpp-2020-hw pull request #3
Opened 2020-10-03 15:49 UTC by GreySR

2020-10-15 22:26 UTC, xterrafunny requested changes

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +	const double EPSILON = 1e-7;
Отступ в 2 пробела

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +	std::vector<double> operator+ (const std::vector<double> &a, const std::vector<double> &b){
Не нужен пробел перед списком аргументов

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +		std::vector<double> c;
Зачем заставлять вектор расширяться через `push_back`, если его размер известен

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +		for (size_t i = 0; i < a.size(); ++i) os << a[i] << " ";
Тело цикла лучше писать на следующей строке

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +		if ((1. - (a * b) / (d1 * d2) < EPSILON) || (1. + (a * b) / (d1 * d2) < EPSILON))
А если векторы нулевые?

2020-10-15 22:26 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +		return (a * b > 0) && (a || b);
А если векторы нулевые

2020-10-31 22:07 UTC, merged

2020-10-31 22:07 UTC, SweetWeakness commented
Исправлений долго не было, приняли, но снизили вам баллы